import { IHash } from '../interfaces/interfaces'


export const departaments = [
    'Atlántida',
    'Colón',
    'Comayagua',
    'Copán',
    'Cortés',
    'Choluteca',
    'El Paraiso',
    'Francisco Morazán',
    'Gracias a Dios',
    'Intibucá',
    'Islas de la Bahía',
    'La Paz',
    'Lempira',
    'Ocotepeque',
    'Olancho',
    'Santa Barbara',
    'Valle',
    'Yoro',
]

export const getProvinces = (departament: string) => {
    const provinces: IHash = {
        'Atlántida': [
            'La Ceiba',
            'El Porvenir',
            'Esparta',
            'Jutiapa',
            'La Masica',
            'Tela',
            'San Franciso',
            'Arizona', 
        ],

        'Colón': [
            'Trujillo',
            'Balfate',
            'Iriona',
            'Limón',
            'Sabá',
            'Santa Fe',
            'Santa Rosa de Aguán',
            'Sonaguera',
            'Tocoa',
            'Bonito Oriental', 
        ],

        'Comayagua': [
            'Comayagua',
            'Ajuterique',
            'El Rosario',
            'Esquías',
            'Humuya',
            'La Libertad',
            'Lamaní',
            'La Trinidad',
            'Lejamaní',
            'Meámbar',
            'Minas de Oro',
            'Ojo de Agua',
            'San Jerónimo',
            'San José de Comayagua',
            'San José del Potrero',
            'San Luis',
            'San Sebastián',
            'Siguatepeque',
            'Villa de San Antonio',
            'Lajas',
            'Taulabe', 
        ],

        'Copán': [
            'Santa Rosa de Copán',
            'Cabañas',
            'Concepción',
            'Copán Ruinas',
            'Corquín',
            'Cucuyagua',
            'Dolores',
            'Dulce Nombre',
            'El Paraiso',
            'Florida',
            'La Jigua',
            'La Unión',
            'Nueva Arcadia',
            'San Agustín',
            'San Antonio',
            'San Jerónimo',
            'San José',
            'San Juan de Opoa',
            'San Nicolás',
            'San Pedro',
            'Santa Rita',
            'Trinidad de Copán',
            'Veracruz', 
        ],

        'Cortés': [
            'San Pedro Sula',
            'Choloma',
            'Omoa',
            'Pimienta',
            'Potrerillos',
            'Puerto Cortés',
            'San Antonio de Cortés',
            'San Francisco de Yojoa',
            'San Manuel',
            'Santa Cruz de Yojoa',
            'Villanueva',
            'La Lima', 
        ],

        'Choluteca': [
            'Choluteca',
            'Apacilagua',
            'Concepción de María',
            'Duyure',
            'El Corpus',
            'El Triunfo',
            'Marcovia',
            'Morolica',
            'Namasigue',
            'Orocuina',
            'Pespire',
            'San Antonio de Flores',
            'San Isidro',
            'San José',
            'San Marcos de Colón',
            'Santa Ana de Yusguare', 
        ],

        'El Paraiso': [
            'Yuscarán',
            'Alauca',
            'Danlí',
            'El Paraiso',
            'Guinope',
            'Jacaleapa',
            'Liure',
            'Morocelí',
            'Oropolí',
            'Potrerillos',
            'San Antonio de Flores',
            'San Lucas',
            'San Matías',
            'Soledad',
            'Teupasenti',
            'Texiguat',
            'Vado Ancho',
            'Yauyupe',
            'Trojes', 
        ],

        'Francisco Morazán': [
            'Tegucigalpa',
            'Alubarén',
            'Cedros',
            'Curarén',
            'El Porvenir',
            'Guaimaca',
            'La Libertad',
            'La Venta',
            'Lepaterique',
            'Maraita',
            'Marale',
            'Nueva Armenia',
            'Ojojona',
            'Orica',
            'Reitoca',
            'Sabanagrande',
            'San Antonio de Oriente',
            'San Ignacio',
            'San Juan de Flores',
            'San Miguelito',
            'Santa Ana',
            'Santa Lucía',
            'Talanga',
            'Tatumbla',
            'Valle de Ángeles',
            'Villa de San Francisco',
            'Vallecillo', 
        ],

        'Gracias a Dios': [
            'Puerto Lempira',
            'Brus Laguna',
            'Ahuas',
            'Juan Francisco Bulnes',
            'Villeda Morales',
            'Wampusirpi', 
        ],

        'Intibucá': [
            'La Esperanza',
            'Camasca',
            'Colomoncagua',
            'Concepción',
            'Dolores',
            'Intibucá',
            'Jesús de Otoro',
            'Magdalena',
            'Masaguara',
            'San Antonio',
            'San Isidro',
            'San Juan del Caite',
            'San Marcos de la Sierra',
            'San Miguelito',
            'Santa Lucía',
            'Yamaranguila',
            'San Francisco de Opalaca', 
        ],

        'Islas de la Bahía': [
            'Roatán',
            'Guanaja',
            'José Santos Guardiola',
            'Utila', 
        ],

        'La Paz': [
            'La Paz',
            'Aguanqueterique',
            'Cabañas',
            '"Cane", ',
            'Chinacla',
            'Guajiquiro',
            'Lauterique',
            'Marcala',
            'Mercedes de Oriente',
            'Opatoro',
            'San Antonio del Norte',
            'San José',
            'San Juan',
            'San Pedro de Tutule',
            'Santa Lucía',
            'Santa Ana',
            'Santa Elena',
            'Santa María',
            'Santiago Puringla',
            'Yarula', 
        ],

        'Lempira': [
            'Gracias',
            'Belén',
            'Candelaria',
            'Cololaca',
            'Erandique',
            'Gualcinse',
            'Guarita',
            'La Campa',
            'La Iguala',
            'Las Flores',
            'San Isidro',
            'La Unión',
            'La Virtud',
            'Lepaera',
            'Mapulaca',
            'Piraera',
            'San Andrés',
            'San Francisco',
            'San Juan Guarita',
            'San Manuel Colohete',
            'San Rafael',
            'San Sebastián',
            'Santa Cruz',
            'Talgua',
            'Tambla',
            'Tomalá',
            'Valladolid',
            'Virginia',
            'San Marcos de Caiquín', 
        ],

        'Ocotepeque': [
            'Nueva Ocotepeque',
            'Belén Gualcho',
            'Concepción',
            'Dolores Merendón',
            'Fraternidad',
            'Intibucá',
            'La Encarnación',
            'La Labor',
            'Lucerna',
            'Mercedes',
            'San Fernando',
            'San Francisco del Valle',
            'San Jorge',
            'San Marcos',
            'Santa Fe',
            'Sensenti',
            'Sinuapa', 
        ],

        'Olancho': [
            'Juticalpa',
            'Campamento',
            'Colomoncagua',
            'Catacamas',
            'Concordia',
            'Dulce Nombre de Culmí',
            'El Rosario',
            'Esquipulas del Norte',
            'Gualaco',
            'Guarizama',
            'Guata',
            'Guayape',
            'Jano',
            'La Unión',
            'Mangulile',
            'Manto',
            'Salamá',
            'San Esteban',
            'San Francisco de Becerra',
            'San Francisco de La Paz',
            'Santa María del Real',
            'Silca',
            'Yocón',
            'Patuca', 
        ],

        'Santa Bárbara': [
            'Santa Bárbara',
            'Arada',
            'Atima',
            'Azacualpa',
            'Ceguaca',
            'Colinas',
            'Concepción del Norte',
            'Concepción del Sur',
            'Chinda',
            'El Níspero',
            'Gualala',
            'Ilama',
            'Macuelizo',
            'Naranjito',
            'Nueva Celilac',
            'Petoa',
            'Protección',
            'Quimistán',
            'San Francisco de Ojuera',
            'San Luis',
            'San Marcos',
            'San Nicolás',
            'San Pedro Centenario',
            'Trinidad',
            'Las Vegas',
            'Nueva Frontera', 
        ],

        'Valle': [
            'Nacaome',
            'Alianza',
            'Amapala',
            'Aramecina',
            'Caridad',
            'Goascorán',
            'Langue',
            'San Francisco de Coray',
            'San Lorenzo', 
        ],

        'Yoro': [
            'Yoro',
            'Arenal',
            'El Negrito',
            'El Progreso',
            'Jocón',
            'Morazán',
            'Olanchito',
            'Santa Rita',
            'Sulaco',
            'Victoria',
            'Yorito', 
        ]
    }

    return provinces[departament];
}
